name: flutter_recaptcha_v2
description: A Flutter plugin for Google ReCaptcha V2.

homepage: https://github.com/senzil/flutter_recaptcha_v2/

version: 0.2.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

